apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: djangoserver
  name: djangoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: djangoserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: djangoserver
    spec:
      containers:
      - image: us.icr.io/sn-labs-andresfeli74/djangoserver:1
        imagePullPolicy: Always
        name: djangoserver
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: SONGS_URL
          value: "http://songs-sn-labs-andresfeli74.labs-prod-openshift-san-a45631dc5778dc6371c67d206ba9ae5c-0000.us-east.containers.appdomain.cloud"
        - name: PICTURES_URL
          value: "https://pictures.1uyzccu73vje.us-south.codeengine.appdomain.cloud"
      restartPolicy: Always
